name: mpitfinal
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  firebase_database: ^6.1.2
  firebase_core: ^1.1.1
  scrollable_list_tabview: ^0.1.6
  onesignal_flutter: ^2.6.3
  flutter_launcher_icons: ^0.9.0
  cupertino_icons: ^1.0.2
  carousel_slider: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo1.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Century
      fonts:
        - asset: assets/fonts/CenturyGothic.ttf
          weight: 400
        - asset: assets/fonts/CenturyGothic-Bold.ttf
          weight: 700

  assets:
    - assets/images/

  uses-material-design: true
